# Generated by Django 6.0.3 on 2026-04-01 05:28

import apps.testing.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single_choice', 'Один вариант'), ('multiple_choice', 'Несколько вариантов'), ('text', 'Текстовый ответ'), ('code', 'Код')], default='single_choice', max_length=20, verbose_name='Тип')),
                ('language', models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('', '—')], default='', max_length=20, verbose_name='Язык')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['test', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('level', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Уровень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Необязательное название для удобства (напр. "Группа A, 01.04.2026")', max_length=255, verbose_name='Название сессии')),
                ('key', models.CharField(db_index=True, default=apps.testing.models._generate_key, max_length=64, unique=True, verbose_name='Ключ сессии')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('running', 'Идёт'), ('finished', 'Завершена')], default='created', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('expires_at', models.DateTimeField(default=apps.testing.models._default_expires, verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='testing.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255, verbose_name='Имя студента')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('score', models.FloatField(default=0.0, verbose_name='Балл (0–100)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('finished', 'Завершена'), ('expired', 'Просрочена')], db_index=True, default='active', max_length=10, verbose_name='Статус')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testing.testsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('selected_options', models.JSONField(default=list, verbose_name='Выбранные варианты (UUID)')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно?')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Отвечено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.studentattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'order'], name='testing_que_test_id_d08a90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattempt',
            unique_together={('session', 'student_name')},
        ),
    ]
