# Generated by Django 6.0.3 on 2026-03-30 20:45

import apps.testing.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('', '—')], default='', max_length=20, verbose_name='Язык программирования'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default=apps.testing.models._generate_key, max_length=64, unique=True, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(default=apps.testing.models._default_expires, verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='testing.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Сессия теста',
                'verbose_name_plural': 'Сессии тестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255, verbose_name='Имя студента')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('score', models.FloatField(default=0.0, verbose_name='Балл (0–100)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testing.testsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Попытка студента',
                'verbose_name_plural': 'Попытки студентов',
                'ordering': ['-started_at'],
                'unique_together': {('session', 'student_name')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('selected_options', models.JSONField(default=list, verbose_name='Выбранные варианты (UUID)')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно?')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Отвечено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.studentattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
