# Generated by Django 6.0.3 on 2026-04-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answered_at'], 'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='studentattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Попытка прохождения', 'verbose_name_plural': 'Попытки прохождения'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия тестирования', 'verbose_name_plural': 'Сессии тестирования'},
        ),
    ]
