# Generated by Django 6.0.3 on 2026-04-01 02:25

import apps.testing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_question_language_testsession_studentattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AddField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('finished', 'Завершена'), ('expired', 'Просрочена')], db_index=True, default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('running', 'Идёт'), ('finished', 'Завершена')], default='created', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('', '—')], default='', max_length=20, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Один вариант'), ('multiple_choice', 'Несколько вариантов'), ('text', 'Текстовый ответ'), ('code', 'Код')], default='single_choice', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начата'),
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='key',
            field=models.CharField(db_index=True, default=apps.testing.models._generate_key, max_length=64, unique=True, verbose_name='Ключ сессии'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'order'], name='testing_que_test_id_d08a90_idx'),
        ),
    ]
