# Generated by Django 6.0.3 on 2026-04-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_answer_options_alter_studentattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'text')},
        ),
    ]
