# Generated by Django 5.2.12 on 2026-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_question_unique_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='question_test_order_idx',
            old_name='testing_que_test_id_d08a90_idx',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_feedback',
            field=models.TextField(blank=True, verbose_name='Комментарий AI'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка AI (0–10)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('auto', 'Авто'), ('ai', 'AI'), ('manual', 'Вручную')], db_index=True, default='pending', max_length=10, verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='max_attempts_per_student',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Только для режима exam. Пусто = без ограничений.', null=True, verbose_name='Макс. попыток на студента'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='session_type',
            field=models.CharField(choices=[('exam', 'Экзамен'), ('training', 'Тренажёр')], db_index=True, default='exam', max_length=10, verbose_name='Тип сессии'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='title',
            field=models.CharField(blank=True, help_text='Необязательное название (напр. "Группа A, 01.04.2026")', max_length=255, verbose_name='Название сессии'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='answer_attempt_question_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['grading_status'], name='answer_grading_status_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='question_type_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'is_correct'], name='option_question_correct_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['session', 'student_name'], name='attempt_session_student_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['status', 'started_at'], name='attempt_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['status', 'is_active'], name='session_status_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test', 'text'), name='unique_question_text_per_test'),
        ),
        migrations.AddConstraint(
            model_name='studentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'finished'])), fields=('session', 'student_name'), name='unique_active_attempt_per_student_per_session'),
        ),
    ]
