# Generated by Django 5.1.3 on 2026-04-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_rename_testing_que_test_id_d08a90_idx_question_test_order_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0–1)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Балл AI (0–10)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_suggestion',
            field=models.TextField(blank=True, verbose_name='Подсказка AI'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('processing', 'Обрабатывается'), ('auto', 'Авто'), ('ai', 'AI'), ('done', 'Готово'), ('failed', 'Ошибка AI'), ('manual', 'Вручную')], db_index=True, default='pending', max_length=15, verbose_name='Статус проверки'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['grading_status', 'answered_at'], name='answer_grading_status_time_idx'),
        ),
    ]
