# Generated by Django 5.1.3 on 2026-04-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_answer_ai_confidence_answer_ai_score_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentattempt',
            name='unique_active_attempt_per_student_per_session',
        ),
    ]
